<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IsAotCompatible>true</IsAotCompatible>
        <PackageId>Ickler.KnowledgeGraphDotNet.Core</PackageId>
        <Version>0.0.1</Version>
        <Title>KnowledgeGraphDotNet.Core</Title>
        <Authors>Jea</Authors>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\KnowledgeGraphDotNet.Abstract\KnowledgeGraphDotNet.Abstract.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.AI" Version="9.8.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.8"/>
        <PackageReference Include="Neo4j.Driver" Version="5.28.3"/>
    </ItemGroup>

</Project>
